version: '2.1'

services:
  web:
    build: .
    command: "npm run dev"
    volumes:
      ['.:/usr/app/', '/usr/app/node_modules']
    ports:
      ['3000:3000']
    depends_on:
      postgres:
        condition: service_healthy 
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/shoefitdb
      NODE_ENV: development

  postgres:
    ports: 
      ['5432:5432']
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: shoefitdb
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "shoefitdb", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10