version: '2'

services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@192.168.99.100:5432/shoefitdb
      NODE_ENV: development

  postgres:
    ports: 
      - 5432:5432
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: shoefitdb